import Foundation
import Testing

/// Reading the checked-in fixtures.
///
/// Every fixture file is generated by a script under `Tools/` and is byte
/// identical to the Android twin's copy, which is what makes a parity claim
/// checkable rather than asserted.
enum Fixtures {
    /// Decodes a fixture from the test bundle.
    static func load<T: Decodable>(_ type: T.Type, from name: String) throws -> T {
        let url = try #require(
            Bundle.module.url(forResource: "Fixtures/\(name)", withExtension: "json"),
            "fixture \(name).json is missing from the test bundle"
        )
        return try JSONDecoder().decode(type, from: Data(contentsOf: url))
    }
}

/// The official UAX #29 conformance files, as emitted by
/// `Tools/gen-unicode-tables.mjs`.
struct UnicodeConformanceFixture: Decodable {
    struct Case: Decodable {
        /// The expected segments, each a run of code points.
        let clusters: [[UInt32]]
        /// The rule names the Unicode test file annotates the case with.
        let note: String

        /// The case's input value.
        var value: String {
            String(String.UnicodeScalarView(
                clusters.flatMap(\.self).compactMap(Unicode.Scalar.init)
            ))
        }

        /// The expected boundaries, as UTF-16 offsets.
        var expectedOffsets: [Int] {
            var offsets = [0]
            var running = 0
            for cluster in clusters {
                running += cluster
                    .compactMap(Unicode.Scalar.init)
                    .reduce(0) { $0 + Int(UTF16.width($1)) }
                offsets.append(running)
            }
            return offsets
        }
    }

    let unicodeVersion: String
    let grapheme: [Case]
    let word: [Case]
}
